/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkerRouteImport } from './routes/worker'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LegalRouteImport } from './routes/legal'
import { Route as ClientRouteImport } from './routes/client'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorkerQualificationsRouteImport } from './routes/worker.qualifications'
import { Route as WorkerInvoicesRouteImport } from './routes/worker.invoices'
import { Route as ClientLiveRouteImport } from './routes/client.live'

const WorkerRoute = WorkerRouteImport.update({
  id: '/worker',
  path: '/worker',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalRoute = LegalRouteImport.update({
  id: '/legal',
  path: '/legal',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientRoute = ClientRouteImport.update({
  id: '/client',
  path: '/client',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkerQualificationsRoute = WorkerQualificationsRouteImport.update({
  id: '/qualifications',
  path: '/qualifications',
  getParentRoute: () => WorkerRoute,
} as any)
const WorkerInvoicesRoute = WorkerInvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => WorkerRoute,
} as any)
const ClientLiveRoute = ClientLiveRouteImport.update({
  id: '/live',
  path: '/live',
  getParentRoute: () => ClientRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/client': typeof ClientRouteWithChildren
  '/legal': typeof LegalRoute
  '/login': typeof LoginRoute
  '/worker': typeof WorkerRouteWithChildren
  '/client/live': typeof ClientLiveRoute
  '/worker/invoices': typeof WorkerInvoicesRoute
  '/worker/qualifications': typeof WorkerQualificationsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/client': typeof ClientRouteWithChildren
  '/legal': typeof LegalRoute
  '/login': typeof LoginRoute
  '/worker': typeof WorkerRouteWithChildren
  '/client/live': typeof ClientLiveRoute
  '/worker/invoices': typeof WorkerInvoicesRoute
  '/worker/qualifications': typeof WorkerQualificationsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/client': typeof ClientRouteWithChildren
  '/legal': typeof LegalRoute
  '/login': typeof LoginRoute
  '/worker': typeof WorkerRouteWithChildren
  '/client/live': typeof ClientLiveRoute
  '/worker/invoices': typeof WorkerInvoicesRoute
  '/worker/qualifications': typeof WorkerQualificationsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/client'
    | '/legal'
    | '/login'
    | '/worker'
    | '/client/live'
    | '/worker/invoices'
    | '/worker/qualifications'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/client'
    | '/legal'
    | '/login'
    | '/worker'
    | '/client/live'
    | '/worker/invoices'
    | '/worker/qualifications'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/client'
    | '/legal'
    | '/login'
    | '/worker'
    | '/client/live'
    | '/worker/invoices'
    | '/worker/qualifications'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  ClientRoute: typeof ClientRouteWithChildren
  LegalRoute: typeof LegalRoute
  LoginRoute: typeof LoginRoute
  WorkerRoute: typeof WorkerRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/worker': {
      id: '/worker'
      path: '/worker'
      fullPath: '/worker'
      preLoaderRoute: typeof WorkerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal': {
      id: '/legal'
      path: '/legal'
      fullPath: '/legal'
      preLoaderRoute: typeof LegalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client': {
      id: '/client'
      path: '/client'
      fullPath: '/client'
      preLoaderRoute: typeof ClientRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/worker/qualifications': {
      id: '/worker/qualifications'
      path: '/qualifications'
      fullPath: '/worker/qualifications'
      preLoaderRoute: typeof WorkerQualificationsRouteImport
      parentRoute: typeof WorkerRoute
    }
    '/worker/invoices': {
      id: '/worker/invoices'
      path: '/invoices'
      fullPath: '/worker/invoices'
      preLoaderRoute: typeof WorkerInvoicesRouteImport
      parentRoute: typeof WorkerRoute
    }
    '/client/live': {
      id: '/client/live'
      path: '/live'
      fullPath: '/client/live'
      preLoaderRoute: typeof ClientLiveRouteImport
      parentRoute: typeof ClientRoute
    }
  }
}

interface ClientRouteChildren {
  ClientLiveRoute: typeof ClientLiveRoute
}

const ClientRouteChildren: ClientRouteChildren = {
  ClientLiveRoute: ClientLiveRoute,
}

const ClientRouteWithChildren =
  ClientRoute._addFileChildren(ClientRouteChildren)

interface WorkerRouteChildren {
  WorkerInvoicesRoute: typeof WorkerInvoicesRoute
  WorkerQualificationsRoute: typeof WorkerQualificationsRoute
}

const WorkerRouteChildren: WorkerRouteChildren = {
  WorkerInvoicesRoute: WorkerInvoicesRoute,
  WorkerQualificationsRoute: WorkerQualificationsRoute,
}

const WorkerRouteWithChildren =
  WorkerRoute._addFileChildren(WorkerRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  ClientRoute: ClientRouteWithChildren,
  LegalRoute: LegalRoute,
  LoginRoute: LoginRoute,
  WorkerRoute: WorkerRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
