/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkerRouteImport } from './routes/worker'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ClientRouteImport } from './routes/client'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ClientLiveRouteImport } from './routes/client.live'

const WorkerRoute = WorkerRouteImport.update({
  id: '/worker',
  path: '/worker',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientRoute = ClientRouteImport.update({
  id: '/client',
  path: '/client',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientLiveRoute = ClientLiveRouteImport.update({
  id: '/live',
  path: '/live',
  getParentRoute: () => ClientRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/client': typeof ClientRouteWithChildren
  '/login': typeof LoginRoute
  '/worker': typeof WorkerRoute
  '/client/live': typeof ClientLiveRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/client': typeof ClientRouteWithChildren
  '/login': typeof LoginRoute
  '/worker': typeof WorkerRoute
  '/client/live': typeof ClientLiveRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/client': typeof ClientRouteWithChildren
  '/login': typeof LoginRoute
  '/worker': typeof WorkerRoute
  '/client/live': typeof ClientLiveRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/admin' | '/client' | '/login' | '/worker' | '/client/live'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/admin' | '/client' | '/login' | '/worker' | '/client/live'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/client'
    | '/login'
    | '/worker'
    | '/client/live'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  ClientRoute: typeof ClientRouteWithChildren
  LoginRoute: typeof LoginRoute
  WorkerRoute: typeof WorkerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/worker': {
      id: '/worker'
      path: '/worker'
      fullPath: '/worker'
      preLoaderRoute: typeof WorkerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client': {
      id: '/client'
      path: '/client'
      fullPath: '/client'
      preLoaderRoute: typeof ClientRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client/live': {
      id: '/client/live'
      path: '/live'
      fullPath: '/client/live'
      preLoaderRoute: typeof ClientLiveRouteImport
      parentRoute: typeof ClientRoute
    }
  }
}

interface ClientRouteChildren {
  ClientLiveRoute: typeof ClientLiveRoute
}

const ClientRouteChildren: ClientRouteChildren = {
  ClientLiveRoute: ClientLiveRoute,
}

const ClientRouteWithChildren =
  ClientRoute._addFileChildren(ClientRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  ClientRoute: ClientRouteWithChildren,
  LoginRoute: LoginRoute,
  WorkerRoute: WorkerRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
